### ISSUE TITLE
[DOCS] Incorrect claim about uniqueness of user provided document id's

### ISSUE THREAD

**Issue by gidler** [chroma-core/docs#13]
The [User Guide](https://docs.trychroma.com/usage-guide#adding-data-to-a-collection) states:

> Each document must have a unique associated `id`. If you try to `.add` a document with an `id` that already exists in the collection, it will raise an exception.

The below example demonstrates that this is not the case:

```python
import chromadb

client = chromadb.Client()
collection = client.create_collection(name="my_collection")
collection.add(
    documents=['doc1', 'doc2'],
    ids=['id1', 'id1'] # <-- duplicate IDs
)

collection.get(
    ids=["id1"]
)
```
Result:
```
{'ids': ['id1', 'id1'],
 'embeddings': None,
 'documents': ['doc1', 'doc2'],
 'metadatas': [None, None]}
```

Inspecting the implementation for inserting new records in the [add() implementation for duckdb](https://github.com/chroma-core/chroma/blob/main/chromadb/db/duckdb.py#L136-L157) and the [add() implementation for clickhouse](https://github.com/chroma-core/chroma/blob/main/chromadb/db/clickhouse.py#L202-L217) appear to support the statement that uniqueness is not enforced and no exception will be raised.

**Comment by HammadB** [comment]
Thanks!
