### ISSUE TITLE
Typo in docs/embeddings.md

### ISSUE THREAD

**Issue by AlexanderTheLit** [chroma-core/docs#135]
I’m new to this project and wanted to create Embeddings using `val = default_ef("foo") ` and was getting absolutely massive embedding sizes. I think the string `“foo”` gets turned into a list of its chars and then each char gets an embedding. I think it should be `val = default_ef(["foo"]) ` instead.

**Comment by jeffchuber** [comment]
thanks! https://github.com/chroma-core/docs/pull/136
