### ISSUE TITLE
Document how key must exist in where filter

### ISSUE THREAD

**Issue by HammadB** [chroma-core/docs#71]
If a key is not included in a record, but is in the where filter, the record will be ignored by the where filter, there is not implicit value.

**Comment by jeffchuber** [comment]
Confirming the behavior here....

Record 1 metadata:
```js
{
  'type': 'pdf', 
  'filename': test.txt',
  'version': 5
}
```

Record 2 metadata:
```js
{
  'type': 'pdf', 
  'filename': test.txt'
}
```

Query
```
 collection.get(where={"version": {"$ne": 1}})
```

Will return Record 1 but not Record 2.

**Comment by jeffchuber** [comment]
confirmed this is still the case in `0.4.6`

**Comment by jeffchuber** [comment]
[ ] document that this is the case

do we feel strongly that there (1) is a fix, or (2) want to "fix" this?
